### ISSUE TITLE
Schematic change 

### ISSUE THREAD

**Issue by Librix8** [robotra/Open-Source-Stroke-Coach#3]
Why did you put in those two Capacitors between the IC and Gound?

And you will need to power the Enable pin(Datasheet):

"To ensure the power supply to the ESP32 chip during power-up, it is advised to add an RC delay circuit at the EN pin. The recommended setting for the RC delay circuit is usually
R = 10 kΩ and C = 0.1 µF. However, specific parameters should be adjusted based on the power-up timing of the module and the power-up and reset sequence timing of the chip.
For ESP32’s power-up and reset sequence timing diagram, please refer to Section Power Scheme in ESP32 Datasheet"

**Comment by robotra** [comment]
Thank you! I have zero training in EE or adjacent fields so am very much winging it.
